Minor Q-Chem updates
materialsproject/custodian pull request #292
Opened 2023-09-19 18:18 UTC by samblau

This PR fixes a few bugs in the Q-Chem error handlers, adds one new handler, adds some additional tests, and slightly extends post processing scratch file handling.

2023-09-19 18:23 UTC, samblau commented
@janosh This is ready for review/merging. Once merged, I would appreciate it if you could release a new version. Please and thank you!

2023-09-20 23:01 UTC, janosh requested changes

2023-09-20 23:01 UTC, janosh commented on custodian/qchem/jobs.py
> +                os.mkdir(local_scratch)
```suggestion
                os.mkdir(local_scratch, exist_ok=True)
```

2023-09-20 23:01 UTC, janosh commented on test_files/qchem/new_test_files/fileman_cpscf.qin
Not sure what @shyuep's stance on test files is for Custodian but in pymatgen we're trying to move to compressed test files to keep repo size small. Would only entail running `gzip test_files/qchem/new_test_files/fileman_cpscf.qin` and changing the file extension when loading the file in python.

2023-09-21 16:45 UTC, janosh approved these changes

2023-09-21 16:45 UTC, merged