New Gaussian plugin
materialsproject/custodian pull request #325
Opened 2024-03-27 16:06 UTC by rashatwi

Add new job and handler modules for various Gaussian errors along with their unittests. Examples of handled errors include: 

* Convergence failure in optimization and SCF jobs 
* Linear bend formation around some angle in geometry 
* Error in internal coordinate system 
* Insufficient memory 
* Wall time error 

Among others

2024-03-27 17:48 UTC, janosh requested changes
thanks so much @rashatwi! this looks like a lot of great work!

left some comments regarding large test files

2024-03-27 17:48 UTC, janosh commented on tests/files/gaussian/Optimization.chk
it would be great if the tests could be refactored to not need large test files. 16MB files increase the `git clone` for future contributors

2024-03-27 17:48 UTC, janosh commented on tests/files/gaussian/linear_bend.out
for large text files, it's best to gzip or lzma compress them

2024-03-28 03:06 UTC, rashatwi commented on tests/files/gaussian/Optimization.chk
I just replaced the files that are > 8 MB with mock ones

2024-03-28 14:04 UTC, janosh requested changes
Thank you very much! final suggestion: Can you gzip the remaining output files? Doesn't have to be all of them, but at least the ones that have a few hundred lines or more.

2024-03-30 06:47 UTC, janosh commented
thanks @rashatwi. i made a few more changes but don't have permission to push to this PR. could you check the box saying "allow edits from maintainers"?

2024-03-31 06:18 UTC, rashatwi commented
> thanks @rashatwi. i made a few more changes but don't have permission to push to this PR. could you check the box saying "allow edits from maintainers"?

Looks like I cannot "allow edits from maintainers" if I'm doing the PR from an organization account [Please check this](https://github.com/orgs/community/discussions/5634)

2024-03-31 06:47 UTC, janosh commented
i see. i didn't know about this restriction for org forks.

i just pushed a new [`gaussian`](https://github.com/materialsproject/custodian/tree/gaussian) branch with all your changes and my two commits on top

1f8e2a65 move matplotlib import into _monitor_convergence
180990ba add type annotations to GaussianJob

could you have a look at those changes and see if they make sense, esp. in 180990ba? if so, would be great if you could change your target branch on this PR from `master` to `gaussian`, pull my changes into your branch and then add similar type annotations to `custodian/gaussian/handlers.py`. thanks!

2024-04-03 05:21 UTC, rashatwi commented
Done

2024-04-03 05:35 UTC, janosh approved these changes
perfect! thank you very much. 🙏  this is great work 👍

2024-04-03 05:35 UTC, merged